# This is the configuration file for the Command-Line Ruby Session-Based Testing framework
# Note: when editing this file, never use tabs for indenting - use spaces instead

# Identify yourself. This will uniquely identify your sessions.
# You may specify either 2 or 3 initials
tester_ID:
  full name: 
  initials:  

# Set an option to 'true' if you include the section in your session sheets
scan_options:
  LTTD:       false
  Areas:      true
  Duration:   true
  TBS:        true
  C vs O:     true
  Data Files: true
  Warnings:   false

# Folders - specify absolute or relative paths
# Relative paths start from the script run location - e.g. starting from c:\sessions
folders:
  data_dir:         datafiles
  metrics_dir:      reports
  report_dir:       reports
  report_templates: config/templates
  todo_dir:         todo

# If you blank out the filename, output will be written to the console
output:
  logfile: scan.log

# All times are specified in minutes
timebox:
  short:   60
  normal:  90
  long:   120
  allowable_session_overlap: 10
